package uk.org.tryharder.twittersplitter
{
	/**
	 * Holds a token (whitespace separated word, URL or twitter name) generated by TweetParser
	 */
	public class TweetToken
	{
		public function TweetToken(type:TweetTokenTypes, text:String)
		{
			_type = type;
			_text = text;
		}
		
		public function get type():TweetTokenTypes { return _type; }
		public function get text():String { return _text; }

		public function toString():String
		{
			return "[" + typePrefix + text + "]";
		}
		
		private function get typePrefix():String
		{
			if (type == TweetTokenTypes.TWITTER_NAME)
			{
				return "tittername:";
			}
			else if (type == TweetTokenTypes.URL)
			{
				return "url:";
			}
			else
			{
				return "";
			}
		}
		
		private var _type:TweetTokenTypes;
		private var _text:String;
	}
}