package uk.org.tryharder.twittersplitter
{
	/**
	 * Types of token generated by the TweetParser: urls, twitter names and everything else (words.)
	 */
	public class TweetTokenTypes
	{
		public static const WORD:TweetTokenTypes = new TweetTokenTypes("Word");
		public static const URL:TweetTokenTypes = new TweetTokenTypes("URL");
		public static const TWITTER_NAME:TweetTokenTypes = new TweetTokenTypes("Twitter name");
		
		// Runtime lock mechanism. Prevents new instantiations of TweetTokenTypes once the constants
		// above have been created.
		private static var locked:Boolean;
		{  locked = true; }
		
		public function TweetTokenTypes(name:String)
		{
			if (locked) 
			{ 
				throw new Error("Cannot instantiate new enumeration values at runtime."); 
			}
			else
			{
				_name = name;
			}
		}

		public function toString():String
		{
			return _name;
		}
		
		private var _name:String;
	}
}